language: generic 
sudo:  required
services: 
  - docker

-before_install:
  - docker build -t nikola/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true nikola/docker-react npm run test